<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ZWEB_TAX_REQUEST">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="import">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="I_GUEST_COUNTRY"/>
                            <xs:element type="xs:string" name="I_GUEST_REGION"/>
                            <xs:element type="xs:string" name="I_SH_NBR"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>