{
"ZFM_PDF_DOC": {
"import": {
"I_SALES_DOC_REQ": {
"SEARCHPARAMS": {
"SALESDOCUMENT": "121041254",
"OUTPUTAPPLICATION": "V1"
},
"OUTPUT_TYPE": {
"CONDITIONTYPE": "BASP",
"GET_PDF": "true"
}
}
},
"export": {
"E_OUTPUT": {
"SALESDOCUMENT": "0121041254",
"CONDITIONTYPE": "BASP",
"KSCHL_TEXT": "Order Ackn. Spool",
"PDF_B64STR": "JVB"
}
}
}
}